name: test

on:
  push:
    branches: [main, dev]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: sudo apt-get update && sudo apt-get install -y libvdeplug-dev
      - run: go vet ./... && go test ./...